puts %{
; generated by intr.S.rb
; do not edit

[section .text]
[extern  int_handler]

_int_common_stub:
    pusha
    push ds
    push es
    push fs
    push gs
    mov ax, 0x10
    mov ds, ax
    mov es, ax
    mov fs, ax
    mov gs, ax
    mov eax, esp
    push eax
    mov eax, int_handler
    call eax
    pop eax
    pop gs
    pop fs
    pop es
    pop ds
    popa
    add esp, 8
    iret

}

0.upto(255) do |i|
  puts %{
    [global _int#{i}]
    _int#{i}:
      #{'push  byte 0' if i!=17 and (i<8 or i>14)}
      push  byte #{i}
      jmp   _int_common_stub
  }
end

# generate the vector table
puts %{
; vector table
[section .data]
[global  _intv]

_intv:
}
0.upto(255) do |i|
  puts "  dd _int#{i}"
end
